#pragma once

#define ORYX_CONFIGURATOR

#define RGB_DISABLE_WHEN_USB_SUSPENDED
#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define CAPS_LOCK_STATUS

#define TAPPING_TOGGLE 2
#define IGNORE_MOD_TAP_INTERRUPT

#define WAIT_FOR_USB

#define COMBO_VARIABLE_LEN
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_TERM 20
#define COMBO_STRICT_TIMER

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define AUTO_SHIFT_TIMEOUT 145
#define TAPPING_TERM 200
#define TAP_CODE_DELAY 20

#define MOONLANDER_USER_LEDS
