#pragma once

#define ORYX_CONFIGURATOR

#define RGB_DISABLE_WHEN_USB_SUSPENDED
#undef RGB_DISABLE_TIMEOUT
#define RGB_DISABLE_TIMEOUT 300000

#define CAPS_LOCK_STATUS

#define TAPPING_TOGGLE 2
#define IGNORE_MOD_TAP_INTERRUPT

#define WAIT_FOR_USB

#define COMBO_COUNT 10
#define COMBO_ONLY_FROM_LAYER 0
